### ISSUE TITLE
Add emotion bootstrapping

### ISSUE THREAD

**Issue by hellrich** [JULIELab/JeSemE#7]
in https://github.com/hellrich/JeSemE/blob/master/pipeline/transform_models/vectors2similarity.py
similar to 
  id2freq.append((year, read_freq(folder, word2id)))
with sim as in
  svd_similarity.append(
            (year, read_generic(folder2svd(folder), word2id, True)))
will update with signature

**Comment by hellrich** [comment]
@buechel 
Please provide a generator such that:

#Input:
   - word2id: dictionary mapping word (lowercase if En, lemma if De) to id
   - method: words to similarity mapping function, use as: sim = method(word1, word2); don't optimise/cache, I will probably provide a dictionary for this myself
   - emotion lexicon (pandas dataframe)– please also provide helper function(s) for parsing

#Output: 
yield tupel of (id, V, A, D)

Upload emotion lexicons and update README accordingly.

**Comment by buechel** [comment]
Which branch should I push to?

**Comment by hellrich** [comment]
Branch to push to:
https://github.com/hellrich/JeSemE/tree/runTimeSimilarity

**Comment by svenbuechel** [comment]
- Code for emotion bootstrapping and loading emotion lexicons is added. 

- Emotion lexicons are NOT added due to legal concerns. 

- Readme is updated with information concerning the emotion lexicons.

Code has not been tested yet due to lack of testing data.

**Comment by svenbuechel** [comment]
@buechel 
Emotion bootstrapping (not normalized so far) lead to some rather strange values:
29,1750,5.08912445603 3.74865752812 5.94961864807
30,1750,**-14.6152436955 -2.98081460606 -12.8481231466**

**Comment by svenbuechel** [comment]
@hellrich , Can similarity be <0 ?

**Comment by hellrich** [comment]
It's a cosine, so yes.

**Comment by hellrich** [comment]
It was a configuration error on my side, code working
