### ISSUE TITLE
Normalize Emotion Scores

### ISSUE THREAD

**Issue by svenbuechel** [JULIELab/JeSemE#8]
To bring out the changing emotion signal over time, the emotion values must be centered and scaled (x-x^/std) for each time step and dimension.

**Comment by hellrich** [comment]
Format of file to center will be
1,1910,0.4 0.5 6
1,1930,0.7 -3 5.55
(id, year/time step, VAD (space-delimmitted))

There will be one such file per corpus.

**Comment by svenbuechel** [comment]
Potential solution implemented in JeSemE/pipeline/transform_models/scale_emotion_data.py. However code has not been tested yet due to lack of data.

**Comment by hellrich** [comment]
Emotion bootstrapping (not normalized so far) lead to some rather strange values:
29,1750,5.08912445603 3.74865752812 5.94961864807
30,1750,**-14.6152436955 -2.98081460606 -12.8481231466**
